sylius_grid:
    grids:
        app_admin_supplier:
            driver:
                name: doctrine/orm
                options:
                    class: AppBundle\Entity\Supplier
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                name:
                    type: twig
                    label: sylius.ui.name
                    path: .
                    options:
                        template: "@SyliusUi/Grid/Field/nameAndDescription.html.twig"
            filters:
                name:
                    type: string
                    label: sylius.ui.search
            actions:
                main:
                    create:
                        type: create
                item:
                    delete:
                        type: delete
                    update:
                        type: update
