sylius_resource:
    resources:
        app.supplier:
            classes:
                model: AppBundle\Entity\Supplier
                form: AppBundle\Form\Type\SupplierType

sylius_order:
    resources:
        order_item:
            classes:
                model: AppBundle\Entity\OrderItem

sylius_product:
    resources:
        product:
            classes:
                model: AppBundle\Entity\Product
