sylius_resource:
    resources:
        app.supplier:
            classes:
                model: AppBundle\Entity\Supplier

sylius_order:
    resources:
        order_item:
            classes:
                model: AppBundle\Entity\OrderItem
