# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_admin:
    resource: '@SyliusAdminBundle/Resources/config/routing.yml'
    prefix: /admin

sylius_api:
    resource: '@SyliusAdminApiBundle/Resources/config/routing.yml'
    prefix: /api

sylius_shop:
    resource: '@SyliusShopBundle/Resources/config/routing.yml'
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

sylius_shop_payum:
    resource: '@SyliusShopBundle/Resources/config/routing/payum.yml'

sylius_shop_default_locale:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.locale_switch:switchAction

_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.xml'

app_admin_api_supplier:
    prefix: /api
    resource: |
        alias: app.supplier
        section: admin_api
    type: sylius.resource_api

app_admin_supplier:
    prefix: /admin
    resource: |
        alias: app.supplier
        templates: SyliusAdminBundle:Crud
        section: admin
        except: ['show']
        grid: app_admin_supplier
    type: sylius.resource
