# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_admin:
    resource: '@SyliusAdminBundle/Resources/config/routing.yml'
    prefix: /admin

sylius_api:
    resource: '@SyliusAdminApiBundle/Resources/config/routing.yml'
    prefix: /api

sylius_shop:
    resource: '@SyliusShopBundle/Resources/config/routing.yml'
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

sylius_shop_payum:
    resource: '@SyliusShopBundle/Resources/config/routing/payum.yml'

sylius_shop_default_locale:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.locale_switch:switchAction

_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.xml'

app_admin_api_supplier:
    prefix: /api
    resource: |
        alias: app.supplier
        section: admin_api
    type: sylius.resource_api

app_admin_supplier:
    prefix: /admin
    resource: |
        alias: app.supplier
        templates: SyliusAdminBundle:Crud
        section: admin
        except: ['show']
        grid: app_admin_supplier
        vars:
            index:
                icon: sliders
    type: sylius.resource

app_admin_order_item_return:
    path: /order-item/{id}/return
    methods: [PUT]
    defaults:
        _controller: sylius.controller.order_item:applyStateMachineTransitionAction
        _sylius:
            permission: true
            state_machine:
                graph: app_order_item
                transition: return
            redirect: referer
            flash: app.order_item.returned


app_admin_ajax_suppliers_by_phrase:
    path: /admin/ajax/suppliers/search
    methods: [GET]
    defaults:
        _controller: app.controller.supplier:indexAction
        _sylius:
            permission: true
            repository:
                method: findByPhrase
                arguments:
                    phrase: $phrase
        _format: json

app_admin_ajax_suppliers_by_codes:
    path: /
    methods: [GET]
    defaults:
        _controller: app.controller.supplier:indexAction
        _sylius:
            permission: true
            repository:
                method: findByCode
                arguments: $code
        _format: json
